<a href="https://colab.research.google.com/github/kimsooyoung/pytorch_til/blob/main/basic_tutorial/1_tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np

데이터로부터 직접(directly) 생성하기

In [ ]:
data = [[1,2], [3,4]]
x_data = torch.tensor(data)

NumPy 배열로부터 생성하기

In [ ]:
np_arr = np.array(data)
x_np = torch.tensor(np_arr)

다른 텐서로부터 생성하기:

In [ ]:
x_ones = torch.ones_like(x_data) # x_data의 속성을 유지합니다.
print(f"Ones Tensor: \n {x_ones} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 



In [ ]:
x_rand = torch.rand_like(x_data, dtype=torch.float) # x_data의 속성을 덮어씁니다.
print(f"Random Tensor: \n {x_rand} \n")

Random Tensor: 
 tensor([[0.1264, 0.2436],
        [0.8944, 0.3017]]) 



무작위(random) 또는 상수(constant) 값을 사용하기:

shape 은 텐서의 차원(dimension)을 나타내는 튜플(tuple)로, 아래 함수들에서는 출력 텐서의 차원을 결정합니다.

In [ ]:
shape = (2,3,) # 쉼표 하나 더 붙이는 것은 관습인 것 같다.
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.6110, 0.1384, 0.5931],
        [0.9523, 0.1916, 0.1194]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


텐서의 속성(Attribute)

In [ ]:
tensor = torch.rand(3,4) # columns 3 / rows 4

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


텐서 연산(Operation)

In [ ]:
if torch.cuda.is_available():
  tensor = tensor.to("cuda")
print(f"Device tensor is stored on: {tensor.device}")

Device tensor is stored on: cuda:0


NumPy식의 표준 인덱싱과 슬라이싱:

In [ ]:
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[:,1] = 0
print(tensor)

First row: tensor([0.9707, 0.3103, 0.3791, 0.2772], device='cuda:0')
First column: tensor([0.9707, 0.9246, 0.7975], device='cuda:0')
Last column: tensor([0.2772, 0.4052, 0.5682], device='cuda:0')
tensor([[0.9707, 0.0000, 0.3791, 0.2772],
        [0.9246, 0.0000, 0.4795, 0.4052],
        [0.7975, 0.0000, 0.3255, 0.5682]], device='cuda:0')


텐서 합치기

In [ ]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[0.9707, 0.0000, 0.3791, 0.2772, 0.9707, 0.0000, 0.3791, 0.2772, 0.9707,
         0.0000, 0.3791, 0.2772],
        [0.9246, 0.0000, 0.4795, 0.4052, 0.9246, 0.0000, 0.4795, 0.4052, 0.9246,
         0.0000, 0.4795, 0.4052],
        [0.7975, 0.0000, 0.3255, 0.5682, 0.7975, 0.0000, 0.3255, 0.5682, 0.7975,
         0.0000, 0.3255, 0.5682]], device='cuda:0')


산술 연산(Arithmetic operations)

In [ ]:
t = torch.rand(4, 4)
y1 = t @ t.T
y2 = t.matmul(t.T)

y3 = torch.rand_like(y1)
torch.matmul(t, t.T, out=y3)
print(y1, y2, y3)

tensor([[1.4434, 1.1497, 1.3898, 1.1401],
        [1.1497, 1.4209, 1.0970, 0.9370],
        [1.3898, 1.0970, 1.5132, 1.2634],
        [1.1401, 0.9370, 1.2634, 1.1546]]) tensor([[1.4434, 1.1497, 1.3898, 1.1401],
        [1.1497, 1.4209, 1.0970, 0.9370],
        [1.3898, 1.0970, 1.5132, 1.2634],
        [1.1401, 0.9370, 1.2634, 1.1546]]) tensor([[1.4434, 1.1497, 1.3898, 1.1401],
        [1.1497, 1.4209, 1.0970, 0.9370],
        [1.3898, 1.0970, 1.5132, 1.2634],
        [1.1401, 0.9370, 1.2634, 1.1546]])


단일-요소(single-element)

텐서 텐서의 모든 값을 하나로 집계(aggregate)하여 요소가 하나인 텐서의 경우, item() 을 사용하여 Python 숫자 값으로 변환할 수 있습니다:

In [ ]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

5.127335071563721 <class 'float'>


바꿔치기(in-place)

연산 연산 결과를 피연산자(operand)에 저장하는 연산을 바꿔치기 연산이라고 부르며, _ 접미사를 갖습니다. 예를 들어: x.copy_(y) 나 x.t_() 는 x 를 변경합니다.

바꿔치기 연산은 메모리를 일부 절약하지만, 기록(history)이 즉시 삭제되어 도함수(derivative) 계산에 문제가 발생할 수 있습니다. 따라서, 사용을 권장하지 않습니다.



In [ ]:
print(f"{tensor} \n")
tensor.add_(5)
print(tensor)

tensor([[0.9707, 0.0000, 0.3791, 0.2772],
        [0.9246, 0.0000, 0.4795, 0.4052],
        [0.7975, 0.0000, 0.3255, 0.5682]], device='cuda:0') 

tensor([[5.9707, 5.0000, 5.3791, 5.2772],
        [5.9246, 5.0000, 5.4795, 5.4052],
        [5.7975, 5.0000, 5.3255, 5.5682]], device='cuda:0')


## NumPy 변환(Bridge)

CPU 상의 텐서와 NumPy 배열은 메모리 공간을 공유하기 때문에, 하나를 변경하면 다른 하나도 변경됩니다.



텐서를 NumPy 배열로 변환하기

In [ ]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


텐서의 변경 사항이 NumPy 배열에 반영됩니다.

In [ ]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


NumPy 배열을 텐서로 변환하기

In [ ]:
n = np.ones(5)
t = torch.from_numpy(n)

NumPy 배열의 변경 사항이 텐서에 반영됩니다.

In [ ]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]


torch.tensor를 쓰면 갱신 안된다!

In [ ]:
n2 = np.ones(5)
t2 = torch.tensor(n2)

In [ ]:
np.add(n2, 1, out=n2)
print(f"t2: {t2}")
print(f"n2: {n2}")

t2: tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
n2: [2. 2. 2. 2. 2.]
