<a href="https://colab.research.google.com/github/kimsooyoung/pytorch_til/blob/main/youtube_series/2_introduction_to_pytorch_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

텐서는 PyTorch의 중심적인 데이터 추상화입니다. 이 대화형 노트북에서는 `Torch.Tensor` 클래스에 대해 자세히 설명합니다.

먼저 **PyTorch** 모듈을 가져오겠습니다. 예제의 일부를 쉽게 만들 수 있도록 PyTorch의 math 모듈도 추가하겠습니다.

In [ ]:
import torch
import math

## Creating Tensors

The simplest way to create a tensor is with the `torch.empty()` call:

In [ ]:
x = torch.empty(3, 4)
print(type(x))
print(x)

<class 'torch.Tensor'>
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


Let’s unpack what we just did:

- We created a tensor using one of the numerous factory methods attached to the torch module.
- The tensor itself is 2-dimensional, having 3 rows and 4 columns.
- The type of the object returned is torch.Tensor, which is an alias for torch.FloatTensor; by default, PyTorch tensors are populated with 32-bit floating point numbers. (More on data types below.)
- You will probably see some random-looking values when printing your tensor. The torch.empty() call allocates memory for the tensor, but does not initialize it with any values - so what you’re seeing is whatever was in memory at the time of allocation.

A brief note about tensors and their number of dimensions, and terminology:
- You will sometimes see a 1-dimensional tensor called a vector.
- Likewise, a 2-dimensional tensor is often referred to as a matrix.
- Anything with more than two dimensions is generally just called a tensor.

More often than not, you’ll want to initialize your tensor with some value. Common cases are all zeros, all ones, or random values, and the torch module provides factory methods for all of these:

In [ ]:
zeros = torch.zeros(2, 3)
print(zeros)

ones = torch.ones(2, 3)
print(ones)

torch.manual_seed(1729)
random = torch.rand(2, 3)
print(random)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])


### Random Tensors and Seeding

In [ ]:
torch.manual_seed(1729)
random1 = torch.rand(2, 3)
print(random1)

random2 = torch.rand(2, 3)
print(random2)

torch.manual_seed(1729)
random3 = torch.rand(2, 3)
print(random3)

random4 = torch.rand(2, 3)
print(random4)

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


What you should see above is that random1 and random3 carry identical values, as do random2 and random4. Manually setting the RNG’s seed resets it, so that identical computations depending on random number should, in most settings, provide identical results.

For more information, see the PyTorch documentation on reproducibility.

### Tensor Shapes

Often, when you’re performing operations on two or more tensors, they will need to be of the same shape - that is, having the same number of dimensions and the same number of cells in each dimension. For that, we have the `torch.*_like()` methods:



In [ ]:
x = torch.empty(2, 2, 3)
print(x.shape)
print(x)

empty_like_x = torch.empty_like(x)
print(empty_like_x.shape)
print(empty_like_x)

zeros_like_x = torch.zeros_like(x)
print(zeros_like_x.shape)
print(zeros_like_x)

ones_like_x = torch.ones_like(x)
print(ones_like_x.shape)
print(ones_like_x)

rand_like_x = torch.rand_like(x)
print(rand_like_x.shape)
print(rand_like_x)

torch.Size([2, 2, 3])
tensor([[[-7.9933e-08,  7.0065e-45,  0.0000e+00],
         [ 0.0000e+00,  1.4013e-45,  0.0000e+00]],

        [[ 0.0000e+00,  4.3474e-41,  1.3452e-43],
         [ 0.0000e+00,  6.7262e-44,  0.0000e+00]]])
torch.Size([2, 2, 3])
tensor([[[-9.4782e-04,  3.2726e-41, -9.4778e-04],
         [ 3.2726e-41,  8.9683e-44,  0.0000e+00]],

        [[ 1.1210e-43,  0.0000e+00,  1.5706e-34],
         [ 3.2733e-41,  1.0256e-08,  2.5783e-09]]])
torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 2, 3])
tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])
torch.Size([2, 2, 3])
tensor([[[0.6128, 0.1519, 0.0453],
         [0.5035, 0.9978, 0.3884]],

        [[0.6929, 0.1703, 0.1384],
         [0.4759, 0.7481, 0.0361]]])


The first new thing in the code cell above is the use of the `.shape` property on a tensor. This property contains a list of the extent of each dimension of a tensor - in our case, x is a three-dimensional tensor with shape 2 x 2 x 3.

Below that, we call the `.empty_like()`, `.zeros_like()`, `.ones_like()`, and `.rand_like()` methods. Using the `.shape` property, we can verify that each of these methods returns a tensor of identical dimensionality and extent.

The last way to create a tensor that will cover is to specify its data directly from a PyTorch collection:

In [ ]:
some_constants = torch.tensor([[3.1415926, 2.71828], [1.61803, 0.0072897]])
print(some_constants)

some_integers = torch.tensor((2, 3, 5, 7, 11, 13, 17, 19))
print(some_integers)

more_integers = torch.tensor(((2, 4, 6), [3, 6, 9]))
print(more_integers)

tensor([[3.1416, 2.7183],
        [1.6180, 0.0073]])
tensor([ 2,  3,  5,  7, 11, 13, 17, 19])
tensor([[2, 4, 6],
        [3, 6, 9]])


Using torch.tensor() is the most straightforward way to create a tensor if you already have data in a Python tuple or list. As shown above, nesting the collections will result in a multi-dimensional tensor.

> `torch.tensor()` creates a copy of the data.

## Tensor Data Types

Setting the datatype of a tensor is possible a couple of ways:

In [ ]:
a = torch.ones((2, 3), dtype=torch.int16)
b = torch.rand((2, 3), dtype=torch.float64) * 20

c = b.to(torch.int32)
print(c)

tensor([[18,  0, 18],
        [ 9,  3, 16]], dtype=torch.int32)


## Math & Logic with PyTorch Tensors

Now that you know some of the ways to create a tensor… what can you do with them?

Let’s look at basic arithmetic first, and how tensors interact with simple scalars:

In [ ]:
ones = torch.zeros( (2, 2) ) + 1
twos = torch.ones( (2, 2) ) * 2
threes = (torch.ones(2, 2) * 7 - 1) / 2
fours = twos ** 2
sqrts = twos ** 0.5

print(ones)
print(twos)
print(threes)
print(fours)
print(sqrts)

tensor([[1., 1.],
        [1., 1.]])
tensor([[2., 2.],
        [2., 2.]])
tensor([[3., 3.],
        [3., 3.]])
tensor([[4., 4.],
        [4., 4.]])
tensor([[1.4142, 1.4142],
        [1.4142, 1.4142]])


As you can see above, arithmetic operations between tensors and scalars, such as addition, subtraction, multiplication, division, and exponentiation are distributed over every element of the tensor. Because the output of such an operation will be a tensor, you can chain them together with the usual operator precedence rules, as in the line where we create threes.

> Similar operations between two tensors also behave like you’d intuitively expect:

In [ ]:
powers2 = twos ** torch.tensor([[1, 2], [3, 4]])
print(powers2)

fives = ones + fours
print(fives)

dozens = threes * fours
print(dozens)

tensor([[ 2.,  4.],
        [ 8., 16.]])
tensor([[5., 5.],
        [5., 5.]])
tensor([[12., 12.],
        [12., 12.]])


## In Brief: Tensor Broadcasting


In [ ]:
rand = torch.rand(2, 4)
doubled = rand * (torch.ones(1, 4) * 2)

print(rand)
print(doubled)

tensor([[0.2024, 0.5731, 0.7191, 0.4067],
        [0.7301, 0.6276, 0.7357, 0.0381]])
tensor([[0.4049, 1.1461, 1.4382, 0.8134],
        [1.4602, 1.2551, 1.4715, 0.0762]])


In [ ]:
rand = torch.rand(2, 4)
temp = rand * torch.tensor([1,1,2,2])

print(rand)
print(temp)

tensor([[0.1332, 0.0023, 0.4945, 0.3857],
        [0.9883, 0.4762, 0.7242, 0.0776]])
tensor([[0.1332, 0.0023, 0.9890, 0.7715],
        [0.9883, 0.4762, 1.4484, 0.1553]])


> What’s the trick here? How is it we got to multiply a 2x4 tensor by a 1x4 tensor?

Broadcasting is a way to perform an operation between tensors that have similarities in their shapes. In the example above, the one-row, four-column tensor is multiplied by both rows of the two-row, four-column tensor.

This is an important operation in Deep Learning. The common example is multiplying a tensor of learning weights by a batch of input tensors, applying the operation to each instance in the batch separately, and returning a tensor of identical shape - just like our (2, 4) * (1, 4) example above returned a tensor of shape (2, 4).

The rules for broadcasting are:
- Each tensor must have at least one dimension - no empty tensors.
- Comparing the dimension sizes of the two tensors, going from last to first:
  - Each dimension must be equal, or
  - One of the dimensions must be of size 1, or
  - The dimension does not exist in one of the tensors

> Tensors of identical shape, of course, are trivially “broadcastable”, as you saw earlier. Here are some examples of situations that honor the above rules and allow broadcasting:

In [ ]:
a =     torch.ones(4, 3, 2)

b = a * torch.rand(   3, 2) # 3rd & 2nd dims identical to a, dim 1 absent
print(b)

c = a * torch.rand(   3, 1) # 3rd dim = 1, 2nd dim identical to a
print(c)

d = a * torch.rand(   1, 2) # 3rd dim identical to a, 2nd dim = 1
print(d)

tensor([[[0.4004, 0.9877],
         [0.0352, 0.0905],
         [0.4485, 0.8740]],

        [[0.4004, 0.9877],
         [0.0352, 0.0905],
         [0.4485, 0.8740]],

        [[0.4004, 0.9877],
         [0.0352, 0.0905],
         [0.4485, 0.8740]],

        [[0.4004, 0.9877],
         [0.0352, 0.0905],
         [0.4485, 0.8740]]])
tensor([[[0.2526, 0.2526],
         [0.6923, 0.6923],
         [0.7545, 0.7545]],

        [[0.2526, 0.2526],
         [0.6923, 0.6923],
         [0.7545, 0.7545]],

        [[0.2526, 0.2526],
         [0.6923, 0.6923],
         [0.7545, 0.7545]],

        [[0.2526, 0.2526],
         [0.6923, 0.6923],
         [0.7545, 0.7545]]])
tensor([[[0.7746, 0.2330],
         [0.7746, 0.2330],
         [0.7746, 0.2330]],

        [[0.7746, 0.2330],
         [0.7746, 0.2330],
         [0.7746, 0.2330]],

        [[0.7746, 0.2330],
         [0.7746, 0.2330],
         [0.7746, 0.2330]],

        [[0.7746, 0.2330],
         [0.7746, 0.2330],
         [0.7746, 0.2330]]])


> Here are some examples of attempts at broadcasting that will fail

In [ ]:
a =     torch.ones(4, 3, 2)

# b = a * torch.rand(4, 3)    # dimensions must match last-to-first
# c = a * torch.rand(   2, 3) # both 3rd & 2nd dims different
# d = a * torch.rand((0, ))   # can't broadcast with an empty tensor

## More Math with Tensors

> PyTorch tensors have over three hundred operations that can be performed on them. Here is a small sample from some of the major categories of operations:

In [ ]:
# common functions
a = torch.rand(2, 4) * 2 - 1
print('Common functions:')
print(torch.abs(a))
print(torch.ceil(a))
print(torch.floor(a))
print(torch.clamp(a, -0.5, 0.5))

# trigonometric functions and their inverses
angles = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4])
sines = torch.sin(angles)
inverses = torch.asin(sines)
print('\nSine and arcsine:')
print(angles)
print(sines)
print(inverses)

# bitwise operations
print('\nBitwise XOR:')
b = torch.tensor([1, 5, 11])
c = torch.tensor([2, 7, 10])
print(torch.bitwise_xor(b, c))

# comparisons:
print('\nBroadcasted, element-wise equality comparison:')
d = torch.tensor([[1., 2.], [3., 4.]])
e = torch.ones(1, 2)  # many comparison ops support broadcasting!
print(torch.eq(d, e)) # returns a tensor of type bool

# reductions:
print('\nReduction ops:')
print(torch.max(d))        # returns a single-element tensor
print(torch.max(d).item()) # extracts the value from the returned tensor
print(torch.mean(d))       # average
print(torch.std(d))        # standard deviation
print(torch.prod(d))       # product of all numbers
print(torch.unique(torch.tensor([1, 2, 1, 2, 1, 2]))) # filter unique elements

# vector and linear algebra operations
v1 = torch.tensor([1., 0., 0.])         # x unit vector
v2 = torch.tensor([0., 1., 0.])         # y unit vector
m1 = torch.rand(2, 2)                   # random matrix
m2 = torch.tensor([[3., 0.], [0., 3.]]) # three times identity matrix

print('\nVectors & Matrices:')
print(torch.cross(v2, v1)) # negative of z unit vector (v1 x v2 == -v2 x v1)
print(m1)
m3 = torch.matmul(m1, m2)
print(m3)                  # 3 times m1
print(torch.svd(m3))       # singular value decomposition

Common functions:
tensor([[0.1018, 0.2531, 0.8823, 0.0156],
        [0.0921, 0.0792, 0.3893, 0.6054]])
tensor([[-0., 1., 1., -0.],
        [1., 1., -0., -0.]])
tensor([[-1.,  0.,  0., -1.],
        [ 0.,  0., -1., -1.]])
tensor([[-0.1018,  0.2531,  0.5000, -0.0156],
        [ 0.0921,  0.0792, -0.3893, -0.5000]])

Sine and arcsine:
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7854, 1.5708, 0.7854])

Bitwise XOR:
tensor([3, 2, 1])

Broadcasted, element-wise equality comparison:
tensor([[ True, False],
        [False, False]])

Reduction ops:
tensor(4.)
4.0
tensor(2.5000)
tensor(1.2910)
tensor(24.)
tensor([1, 2])

Vectors & Matrices:
tensor([ 0.,  0., -1.])
tensor([[0.3285, 0.5655],
        [0.0065, 0.7765]])
tensor([[0.9856, 1.6966],
        [0.0196, 2.3296]])
torch.return_types.svd(
U=tensor([[ 0.6345,  0.7729],
        [ 0.7729, -0.6345]]),
S=tensor([2.9475, 0.7677]),
V=tensor([[ 0.2173,  0.9761],
        [ 0.9761, -0.2173]]))


## Altering Tensors in Place

Most binary operations on tensors will return a third, new tensor. When we say c = a * b (where a and b are tensors), the new tensor c will occupy a region of memory distinct from the other tensors.

There are times, though, that you may wish to alter a tensor in place - for example, if you’re doing an element-wise computation where you can discard intermediate values. For this, most of the math functions have a version with an appended underscore (_) that will alter a tensor in place.

> 별도 변수 저장 없이 바로 해당 변수에 연산 결과 덮어씌우는 방법

In [ ]:
a = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4])
print('a:')
print(a)
print(torch.sin(a))   # this operation creates a new tensor in memory
print(a)              # a has not changed

b = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4])
print('\nb:')
print(b)
print(torch.sin_(b))  # note the underscore
print(b)              # b has changed

a:
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7854, 1.5708, 2.3562])

b:
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7071, 1.0000, 0.7071])


Note that these in-place arithmetic functions are methods on the torch.Tensor object, not attached to the torch module like many other functions (e.g., `torch.sin()`). As you can see from `a.add_(b)`, the calling tensor is the one that gets changed in place.

There is another option for placing the result of a computation in an existing, allocated tensor. Many of the methods and functions we’ve seen so far - including creation methods! - have an out argument that lets you specify a tensor to receive the output. If the out tensor is the correct shape and dtype, this can happen without a new memory allocation:

In [ ]:
a = torch.rand(2, 2)
b = torch.rand(2, 2)
c = torch.zeros(2, 2)
old_id = id(c)

print(c)
d = torch.matmul(a, b, out=c)
print(c)                # contents of c have changed

assert c is d           # test c & d are same object, not just containing equal values
assert id(c) == old_id  # make sure that our new c is the same object as the old one

torch.rand(2, 2, out=c) # works for creation too!
print(c)                # c has changed again
assert id(c) == old_id  # still the same object!

tensor([[0., 0.],
        [0., 0.]])
tensor([[0.5991, 0.7677],
        [0.8968, 1.2237]])
tensor([[0.4704, 0.6077],
        [0.4757, 0.5874]])


## Copying Tensors


In [ ]:
a = torch.ones(2, 2)
b = a

a[0][1] = 561  # we change a...
print(b)       # ...and b is also altered

tensor([[  1., 561.],
        [  1.,   1.]])


In [ ]:
a = torch.ones(2, 2)
b = a.clone()

assert b is not a      # different objects in memory...
print(torch.eq(a, b))  # ...but still with the same contents!

a[0][1] = 561          # a changes...
print(b)               # ...but b is still all ones

tensor([[True, True],
        [True, True]])
tensor([[1., 1.],
        [1., 1.]])


There is an important thing to be aware of when using ``clone()``. If your source tensor has autograd, enabled then so will the clone. This will be covered more deeply in the video on autograd, but if you want the light version of the details, continue on.

In [ ]:
a = torch.rand(2, 2, requires_grad=True) # turn on autograd
print(a)

b = a.clone()
print(b)

c = a.detach().clone()
print(c)

print(a)

tensor([[0.4363, 0.6339],
        [0.3208, 0.4323]], requires_grad=True)
tensor([[0.4363, 0.6339],
        [0.3208, 0.4323]], grad_fn=<CloneBackward0>)
tensor([[0.4363, 0.6339],
        [0.3208, 0.4323]])
tensor([[0.4363, 0.6339],
        [0.3208, 0.4323]], requires_grad=True)


What’s happening here?

- We create a with requires_grad=True turned on. We haven’t covered this optional argument yet, but will during the unit on autograd.
- When we print a, it informs us that the property requires_grad=True - this means that autograd and computation history tracking are turned on.
- We clone a and label it b. When we print b, we can see that it’s tracking its computation history - it has inherited a’s autograd settings, and added to the computation history.
- We clone a into c, but we call detach() first.
- Printing c, we see no computation history, and no requires_grad=True.

The `detach()` method detaches the tensor from its computation history. It says, “do whatever comes next as if autograd was off.” It does this without changing a - you can see that when we print a again at the end, it retains its `requires_grad=True` property.

## Moving to GPU

One of the major advantages of PyTorch is its robust acceleration on CUDA-compatible Nvidia GPUs. (“CUDA” stands for Compute Unified Device Architecture, which is Nvidia’s platform for parallel computing.) So far, everything we’ve done has been on CPU. How do we move to the faster hardware?

> First, we should check whether a GPU is available, with the `is_available()` method.

In [ ]:
if torch.cuda.is_available():
  print("We have a GPU!!")
else:
  print("Sorry, CPU only...")

We have a GPU!!


Once we’ve determined that one or more GPUs is available, we need to put our data someplace where the GPU can see it. Your CPU does computation on data in your computer’s RAM. Your GPU has dedicated memory attached to it. Whenever you want to perform a computation on a device, you must move all the data needed for that computation to memory accessible by that device. (Colloquially, “moving the data to memory accessible by the GPU” is shorted to, “moving the data to the GPU”.)

> There are multiple ways to get your data onto your target device. You may do it at creation time:



In [ ]:
if torch.cuda.is_available():
  gpu_rand = torch.rand(2, 2, device='cuda')
  print(gpu_rand)
else:
  print("Sorry, CPU only...")

tensor([[0.3344, 0.2640],
        [0.2119, 0.0582]], device='cuda:0')


By default, new tensors are created on the CPU, so we have to specify when we want to create our tensor on the GPU with the optional device argument. You can see when we print the new tensor, PyTorch informs us which device it’s on (if it’s not on CPU).

You can query the number of GPUs with torch.cuda.device_count(). If you have more than one GPU, you can specify them by index: device='cuda:0', device='cuda:1', etc.

As a coding practice, specifying our devices everywhere with string constants is pretty fragile. In an ideal world, your code would perform robustly whether you’re on CPU or GPU hardware. You can do this by creating a device handle that can be passed to your tensors instead of a string:



In [ ]:
if torch.cuda.is_available():
    my_device = torch.device('cuda')
else:
    my_device = torch.device('cpu')
print('Device: {}'.format(my_device))

x = torch.rand(2, 2, device=my_device)
print(x)

Device: cuda
tensor([[0.0024, 0.6778],
        [0.2441, 0.6812]], device='cuda:0')


If you have an existing tensor living on one device, you can move it to another with the to() method. The following line of code creates a tensor on CPU, and moves it to whichever device handle you acquired in the previous cell.

In [ ]:
y = torch.rand(2, 2)
y = y.to(my_device)

It is important to know that in order to do computation involving two or more tensors, all of the tensors must be on the same device. The following code will throw a runtime error, regardless of whether you have a GPU device available:

In [ ]:
x = torch.rand(2, 2, device='cuda')
y = torch.rand(2, 2, device='cuda')
z = x + y  # exception will be thrown

## Manipulating Tensor Shapes

> Sometimes, you’ll need to change the shape of your tensor. Below, we’ll look at a few common cases, and how to handle them.

## Changing the Number of Dimensions

One case where you might need to change the number of dimensions is passing a single instance of input to your model. PyTorch models generally expect batches of input.

For example, imagine having a model that works on `3 x 226 x 226` images - a 226-pixel square with 3 color channels. When you load and transform it, you’ll get a tensor of shape (3, 226, 226). Your model, though, is expecting input of shape (N, 3, 226, 226), where N is the number of images in the batch. So how do you make a batch of one?

In [ ]:
a = torch.rand(3, 226, 226)
b = a.unsqueeze(0)

print(a.shape)
print(b.shape)

torch.Size([3, 226, 226])
torch.Size([1, 3, 226, 226])


The `unsqueeze()` method adds a dimension of extent 1. `unsqueeze(0)` adds it as a new zeroth dimension - now you have a batch of one!

So if that’s unsqueezing? What do we mean by squeezing? We’re taking advantage of the fact that any dimension of extent 1 does not change the number of elements in the tensor.

In [ ]:
c = torch.rand(1, 1, 1, 1, 1)
print(c)

tensor([[[[[0.5088]]]]])


Continuing the example above, let’s say the model’s output is a 20-element vector for each input. You would then expect the output to have shape (N, 20), where N is the number of instances in the input batch. That means that for our single-input batch, we’ll get an output of shape (1, 20).

What if you want to do some non-batched computation with that output - something that’s just expecting a 20-element vector?

In [ ]:
a = torch.rand(1, 20)
print(a.shape)
print(a)

b = a.squeeze(0)
print(b.shape)
print(b)

c = torch.rand(2, 2)
print(c.shape)

d = c.squeeze(0)
print(d.shape)

torch.Size([1, 20])
tensor([[0.3142, 0.8068, 0.6503, 0.4621, 0.6882, 0.7282, 0.9156, 0.4836, 0.1451,
         0.7946, 0.4126, 0.1625, 0.9214, 0.2327, 0.5813, 0.7089, 0.3735, 0.9389,
         0.3442, 0.9211]])
torch.Size([20])
tensor([0.3142, 0.8068, 0.6503, 0.4621, 0.6882, 0.7282, 0.9156, 0.4836, 0.1451,
        0.7946, 0.4126, 0.1625, 0.9214, 0.2327, 0.5813, 0.7089, 0.3735, 0.9389,
        0.3442, 0.9211])
torch.Size([2, 2])
torch.Size([2, 2])


dimension value가 1인 경우에만 squeeze를 할 수 있다.

Another place you might use unsqueeze() is to ease broadcasting. Recall the example above where we had the following code:

In [ ]:
a = torch.ones(4, 3, 2)
b = torch.rand(   3)     # trying to multiply a * b will give a runtime error
c = b.unsqueeze(1)       # change to a 2-dimensional tensor, adding new dim at the end
print(c.shape)
print(a * c)             # broadcasting works again!

torch.Size([3, 1])
tensor([[[0.9906, 0.9906],
         [0.0350, 0.0350],
         [0.0411, 0.0411]],

        [[0.9906, 0.9906],
         [0.0350, 0.0350],
         [0.0411, 0.0411]],

        [[0.9906, 0.9906],
         [0.0350, 0.0350],
         [0.0411, 0.0411]],

        [[0.9906, 0.9906],
         [0.0350, 0.0350],
         [0.0411, 0.0411]]])


The squeeze() and unsqueeze() methods also have in-place versions, squeeze_() and unsqueeze_():

In [ ]:
batch_me = torch.rand(3, 226, 226)
print(batch_me.shape)
batch_me.unsqueeze_(0)
print(batch_me.shape)

torch.Size([3, 226, 226])
torch.Size([1, 3, 226, 226])


Sometimes you’ll want to change the shape of a tensor more radically, while still preserving the number of elements and their contents. One case where this happens is at the interface between a convolutional layer of a model and a linear layer of the model - this is common in image classification models. A convolution kernel will yield an output tensor of shape features x width x height, but the following linear layer expects a 1-dimensional input. reshape() will do this for you, provided that the dimensions you request yield the same number of elements as the input tensor has:

> 완전 일자로 피는 극단적인 경우,reshape() 사용

In [ ]:
output3d = torch.rand(6, 20, 20)
print(output3d.shape)

input1d = output3d.reshape(6 * 20 * 20)
print(input1d.shape)

# can also call it as a method on the torch module:
print(torch.reshape(output3d, (6 * 20 * 20,)).shape)

torch.Size([6, 20, 20])
torch.Size([2400])
torch.Size([2400])


## NumPy Bridge

In the section above on broadcasting, it was mentioned that PyTorch’s broadcast semantics are compatible with NumPy’s - but the kinship between PyTorch and NumPy goes even deeper than that.

If you have existing ML or scientific code with data stored in NumPy ndarrays, you may wish to express that same data as PyTorch tensors, whether to take advantage of PyTorch’s GPU acceleration, or its efficient abstractions for building ML models. It’s easy to switch between ndarrays and PyTorch tensors:

> numpy => torch

In [ ]:
import numpy as np

numpy_array = np.ones((2, 3))
print(numpy_array)

pytorch_tensor = torch.from_numpy(numpy_array)
print(pytorch_tensor)

[[1. 1. 1.]
 [1. 1. 1.]]
tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


PyTorch creates a tensor of the same shape and containing the same data as the NumPy array, going so far as to keep NumPy’s default 64-bit float data type.

The conversion can just as easily go the other way:

> torch => numpy

In [ ]:
pytorch_rand = torch.rand(2, 3)
print(pytorch_rand)

numpy_rand = pytorch_rand.numpy()
print(numpy_rand)

tensor([[0.9627, 0.7905, 0.6169],
        [0.6786, 0.8231, 0.1066]])
[[0.9626979  0.7904784  0.61689967]
 [0.6785838  0.8230716  0.1065619 ]]


It is important to know that these converted objects are using the same underlying memory as their source objects, meaning that changes to one are reflected in the other:

> 메모리를 공유하므로 numpy 변수 바꾸면 torch 변수도 바뀜에 유의!

In [ ]:
numpy_array[1, 1] = 23
print(pytorch_tensor)

pytorch_rand[1, 1] = 17
print(numpy_rand)


tensor([[ 1.,  1.,  1.],
        [ 1., 23.,  1.]], dtype=torch.float64)
[[ 0.9626979   0.7904784   0.61689967]
 [ 0.6785838  17.          0.1065619 ]]
